name: wonokitri
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  google_fonts: 6.1.0
  carousel_slider: 4.2.1
  timeline_tile: 2.0.0
  floating_bottom_navigation_bar: 1.5.2
  flutter_datetime_picker: 1.5.1
  intl: 0.19.0
  slide_countdown: 1.6.1
  dotted_line: 3.2.2
  font_awesome_flutter: 10.7.0
  fluttertoast: 8.2.6
  back_button_interceptor: 7.0.3
  flutter_native_splash: 2.4.0
  introduction_screen: 3.1.14
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

# jangan lupa kalo semisal mau ganti image nya nanti di flutter clear dulu, 
# terus flutter pub get, terus flutter pub run build_runner build 

flutter_native_splash: 
  color: '#ffffff'
  image: assets/logo_splash.png
  android: true
  ios: true
  web: false

